@Restaurants_API_HostAddress = http://localhost:5268

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Test Restaurant",
    "Description": "Test Restaurant Description",
    "Category": 3,
    "HasDelivery": true,
    "ContactNumber": "123",
    "ContactEmail": "test@restaurant",
    "City": "Ankara",
    "Street": "Test Street",
    "PostalCode": "0606",
    "Tables": 8
}
